version: '3.8'

services:
  app:
    image: 'bst:last'
    build: ./
    stop_signal: SIGINT
    ports:
      - "8080:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./docs:/usr/share/nginx/html/docs
    environment:
      API_URL: docs/swagger.yaml