// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "welcome page",
                "tags": [
                    "main"
                ],
                "summary": "MainPage",
                "responses": {}
            }
        },
        "/delete": {
            "get": {
                "description": "remove value from BST",
                "tags": [
                    "remove"
                ],
                "summary": "Remove",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "int",
                        "name": "remove",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/insert": {
            "get": {
                "description": "insert value in BST",
                "tags": [
                    "insert"
                ],
                "summary": "Insert",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "int",
                        "name": "insert",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/search": {
            "get": {
                "description": "lookup value in BST",
                "tags": [
                    "search"
                ],
                "summary": "Search",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "int",
                        "name": "search",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BST",
	Description:      "API Server for Search,Insert,Delete value in BST",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
